# Generated by Django 5.0.13 on 2025-06-25 05:51

import utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('audit_id', models.CharField(default=utils.functions.get_uuid, max_length=64, primary_key=True, serialize=False)),
                ('extra_details', models.JSONField(default=None, null=True)),
                ('request_headers', models.JSONField(default=None, null=True)),
                ('user_id', models.CharField(default=None, max_length=64, null=True)),
                ('client_ip', models.CharField(default=None, max_length=128, null=True)),
                ('http_method', models.CharField(default=None, max_length=16, null=True)),
                ('module_name', models.CharField(default=None, max_length=128, null=True)),
                ('request_path', models.CharField(default=None, max_length=256, null=True)),
                ('request_route', models.CharField(default=None, max_length=256, null=True)),
                ('client_user_agent', models.CharField(default=None, max_length=128, null=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
    ]
