# Generated by Django 5.0.13 on 2025-06-25 05:51

import django.db.models.deletion
import utils.functions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('user_id', models.CharField(default=utils.functions.get_uuid, max_length=64, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_name', models.CharField(default=None, max_length=128, null=True)),
                ('first_name', models.CharField(default=None, max_length=128, null=True)),
                ('phone_number', models.CharField(default=None, max_length=128, null=True)),
                ('profile_photo', models.CharField(default=None, max_length=512, null=True)),
                ('password', models.CharField(default=None, max_length=128, null=True)),
                ('date_joined', models.DateTimeField(default=None, null=True)),
                ('role_id', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], max_length=64)),
            ],
            options={
                'db_table': 'auth_users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('permission_id', models.CharField(default=utils.functions.get_uuid, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('module', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=64)),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionMapping',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('role_permission_mapping_id', models.CharField(default=utils.functions.get_uuid, max_length=64, primary_key=True, serialize=False)),
                ('role_id', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('MANAGER', 'Manager'), ('OPERATOR', 'Operator')], max_length=64)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_user.permission')),
            ],
            options={
                'db_table': 'role_permission_mappings',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
