# Generated by Django 5.0.13 on 2025-06-25 05:51

import django.db.models.deletion
import utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('tenant_id', models.CharField(default=utils.functions.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('tenant_code', models.CharField(max_length=256)),
                ('tenant_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantConfiguration',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('tenant_configuration_id', models.CharField(default=utils.functions.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('authentication_type', models.CharField(choices=[('TOKEN', 'Token'), ('JWT_TOKEN', 'JWT Token')], default='TOKEN', max_length=56)),
                ('database_strategy', models.CharField(choices=[('SHARED', 'Shared DB'), ('SEPARATE', 'Separate DB')], default='SHARED', help_text='Defines whether the tenant uses a shared or separate database.', max_length=16)),
                ('database_server', models.CharField(choices=[('SQLITE', 'Sqlite3'), ('POSTGRES', 'Postgres')], default='SQLITE', help_text='Defines which backend database to be use.', max_length=16)),
                ('database_config', models.JSONField(default=None, help_text='Database config like host, port, db-name, password, username etc.', null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'db_table': 'tenant_configurations',
            },
        ),
    ]
