# Generated by Django 5.0.13 on 2025-06-25 05:51

import utils.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant_id', models.CharField(default=None, max_length=128, null=True)),
                ('created_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_by', models.CharField(default=None, max_length=128, null=True)),
                ('updated_dtm', models.DateTimeField(auto_now=True)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('deleted_dtm', models.DateTimeField(default=None, null=True)),
                ('category_id', models.CharField(default=utils.functions.get_uuid, max_length=36, primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=256)),
                ('category_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
